### ISSUE TITLE
handle case when hg prompt not found

### ISSUE THREAD

**Issue by fingermark** [AndrewRayCode/Bash-Prompt-Builder#43]
I'm not exactly sure what hg prompt does, but it'd be nice to use an alternative method if it doesn't exit.

**Comment by AndrewRayCode** [comment]
It's listed in the [requirements list](http://andrewray.me/bash-prompt-builder/index.html#what), it's the fastest prompt display for mercurial. If you want mercurial info in your command line, you need to use it with this repo. If you don't want mercurial in your command line, uncheck the mercurial option

**Comment by AndrewRayCode** [comment]
fun fact: linking to ids on the page doesn't work. I should fix that. It's in the "what is this I don't even" section
